server:
  port: 8080

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #数据源
    password: yangcautious.
    url: jdbc:postgresql://localhost:5433/account?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    driver-class-name: org.postgresql.Driver          #postgresql驱动
  devtools:
    restart:
      enabled: true

mybatis:
  type-aliases-package: com.example.payrollAccounting.entities
  mapper-locations: classpath:/mapper/*.xml
